[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "0x000000"
foreground = "0xC6C6C4"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

# delete line
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.9

[window.dimensions]
columns = 140
lines = 50

[window.padding]
x = 0
y = 0
