[colors.bright]
black = "#696969"
blue = "#007FFF"
cyan = "#a3e0fe"
green = "#29a93e"
magenta = "#ff9ec2"
red = "#FF2400"
white = "#FFFAFA"
yellow = "#ffeb8f"

[colors.normal]
black = "#10100E"
blue = "#0087BD"
cyan = "#66c1ef"
green = "#8aba6e"
magenta = "#ff76a8"
red = "#C40233"
white = "#C6C6C4"
yellow = "#e8d762"

[colors.primary]
background = "#000000"
foreground = "#C6C6C4"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.8

[window.dimensions]
columns = 140
lines = 50

[window.padding]
x = 0
y = 0

# Delete line.
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"
